---
title: "help"
author: "Roman Hüppi"
date: "3 August 2018"
output: html_document
---

## File upload for flux visualisation

The input table should contain the following columns:
#### Experimental design variables
* `treatment_fact1`: First experimental factor of the dataset, i.e. diversification treatment (mixed crop vs. mono crop)
* `treatment_fact2`: Second experimental factor of the dataset, i.e. fertilisation treatment (organic vs. mineral)
* `treatment_fact3`: Third experimental factor, if available, i.e. position of chambers within the plots (row vs. berm)	
* `block`: Using a block design, this can be specified here
* `sub_factor`: Any other sub factor of the experiment...
* `chamber.nr`: This is a factor that contains a label for each individual chamber to look at the fluxes from each chamber separatly, no matter of the treatments.

#### Flux data
* `linear.f0`: Linear least square regression estimate of the flux
* `robust.linear.f0`: A robust linear flux estimate (i.e. from `gasfluxes` of the package: https://cran.r-project.org/web/packages/gasfluxes/index.html) 
* `HMR.f0`: HMR estmate	dynamic.kappa.f0	https://cran.r-project.org/web/packages/HMR/index.html
* `dynamic.kappa.f0`: see https://doi.org/10.1371/journal.pone.0200876 => Depending on the measurement precision this method automatically combines the results from linear, robust linear and HMR to a more reliable flux estimate.

Default unit: *mg N<sub>2</sub>O* or *CH<sub>4</sub> m^-1 h^-1* or *g* for *CO<sub>2</sub>*, any other reasonable flux unit can be used as well.

See the template for flux visualisation: https://github.com/pyroman1337/gasflxvis/blob/master/data/gasflux-N2O_example-input.csv

Note: Separator of `.csv` file is a semicolon "`;`" (can possibly be changed to comma in the future[if gasfluxes avoids the comma in the diagnostics])

## Gasflux calculation 

To calculate fluxes from chamber concentrations, select the second task available in the shiny app menu. The input file for the flux calculation should contain the following columns shown in the example input file:

https://github.com/pyroman1337/gasflxvis/blob/master/data/gasflxvis_gasfluxes_example_input.csv

### Minimal detectable flux (f.detect)

Use the 'minflxlim' shiny app to calculate `f.detect`: https://sae-interactive-data.ethz.ch/minflxlim/
It is suggested to use the same `f.detect` value for the whole dataset. When one of the parameters (i.e. chamber height) varies throughout the dataset, choose the largest flux limit for pragmatic reasons.

You can click on a flux result in the "Gasfluxes" table to see the plot of the chamber calculation by the gasfluxes package (if the flux was calculated on the shiny server).

We highly recommand the use of the combined linear and non-linear approach described in the publication "Restricting the nonlinearity parameter in soil greenhouse gas flux calculation for more reliable flux estimates" (see link above).